# Site settings
title: Bavarian's IT Blog 
email: mr.cyberpower@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://etem.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  etem

# Build settings
markdown: kramdown
