# Site settings
title: Bavarian's blog
tagline: Share the knowledge...
email: mr.cyberpower@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Networker, Cybersecurity enthusiast, Linux addict.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://127.0.0.1" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Etem Hyusnev"
author_thumbnail: "/assets/images/avatar3.png" # Author avatar
# Theme customization - please change from the defaults!
theeme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"

  # Social media links, leave blank to ignore
  social: 
    github: etem
    twitter: hyusnev
    facebook: cyberpower
    gplus: +EtemBavarian
    # dribble: gayanvirajith
    #pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname


  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-53673736-2
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

gems: [jekyll-paginate]

